apiVersion: aifar.io/v1
kind: Runtime
metadata:
  name: demo-nginx
  namespace: prod
spec:
  nodeName: local
  network: aifar-runtime
  deployments:
    - name: nginx
      image: nginx:1.25
      replicas: 0
      selector:
        app: nginx
      ports:
        - name: http
          containerPort: 80
      resources:
        cpus: "0.25"
        memory: 128Mi
  services:
    - name: nginx
      selector:
        app: nginx
      port: 80
      targetPort: http
      listenPort: 19080
  ingress:
    - name: public
      provider: builtin
      listenPort: 18080
      routes:
        - path: /
          serviceName: nginx
          servicePort: 80
